version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './:/app:rw,cached'
      - '/app/node_modules'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'