version: '3.8'

services:
  app:
    build: .
    expose:
      - 3001
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    volumes:
      - './:/app:rw,cached'
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    build: ./grafana
    ports: 
      - 3000:3000

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=name
      - MONGO_INITDB_ROOT_PASSWORD=word
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:
  prometheus_data: