version: '3.8'

services:
  app:
    image: node:20
    working_dir: '/app'
    command: npm start
    volumes:
      - './:/app:rw,cached'
      - '/app/node_modules'
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    entrypoint: npm install

  mongo:
    image: mongo
    ports:
      - '27017:27017'