groups:
  - name: DemoAlerts
    rules:
     - alert: "on app down"
       expr: up{job="app"} < 1
       for: 30s
       labels:
          severity: critical
       annotations:
          summary: 'Critical error: app is down!'
          description: 'Critical error: app is down!'
     - alert: "APP SLOW"
       expr: http_requests_duration_seconds_sum{job="app", path="/users"} > 2
       for: 20s
       labels:
          severity: critical
       annotations:
          summary: 'Critical error: app is slow!'
          description: 'Critical error: app is slow!'