global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'daanakin@gmail.com'
  smtp_auth_username: 'daanakin@gmail.com'
  smtp_auth_password: 'eqbdotrjskjdszxb'

receivers:
  - name: 'email-me'
    email_configs:
      - to: 'dws.vanbragt@student.avans.nl'
        headers:
          subject: 'Prometheus Alert: {{ .Status }}'
        html: |
          <html>
            <body>
              <p>Hello Daan van Bragt,</p>
              <p>Currently there are one or more critical errors within the app.</p>
              <p>Please check Prometheus for more insight into these issues.</p>
              <p>Kind regards,</p>
              <p>A.P.M.S.</p>
            </body>
          </html>

route:
  receiver: 'email-me'
  group_wait: '20s'
  group_interval: '10m'
  repeat_interval: '2h'